import type { Restaurant, Category, Offer, UserProfile } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'all', name: 'All', icon: 'grid_view' },
  { id: 'biryani', name: 'Biryani', icon: 'rice_bowl' },
  { id: 'pizza', name: 'Pizza', icon: 'local_pizza' },
  { id: 'burgers', name: 'Burgers', icon: 'lunch_dining' },
  { id: 'rolls', name: 'Rolls', icon: 'wrap_text' },
  { id: 'thali', name: 'Thali', icon: 'restaurant' },
  { id: 'desserts', name: 'Desserts', icon: 'icecream' },
  { id: 'cafe', name: 'Cafe', icon: 'coffee' },
  { id: 'groceries', name: 'Groceries', icon: 'local_grocery_store' },
];

export const MOCK_OFFERS: Offer[] = [
  {
    id: 'off-1',
    title: '50% OFF on Biryani',
    description: 'Valid on your first order this week in Khunta.',
    code: 'FRETZABIRYANI',
    discount: '50%',
    bgImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAU-8aQY6MZTJF14D7OgMVHJmtm2PfjkCu9U9ojjM8lwK4XDfjjh0K_nRgtKRvxh-E8Rc30hsHQ7JSs4jhaZaqT2NdZxDiy9nA2XfQ5aHYDLIIwi1BXZ3fw3A1oIYG9akLNHKwNUFRdnyxiuCIp21xvOp4XjHSMUK3rJ10amxstvFGyKCuAcrjwC8ZkdiiNdtVx8_obsu2W6fCUhICqXmHP3KIenyVvdIAPf_-NedlFr9wcWKtKtp6dSrl7WsF2glIH56Y0D0iD_A',
  },
  {
    id: 'off-2',
    title: 'Free Delivery above ₹299',
    description: 'Order from any top-rated restaurant in Khunta.',
    code: 'FREESHIP',
    discount: '100% OFF Delivery',
    bgImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPWT-waWRecQTq2KTGIgFv1spM-RjnQoa3yYSfAFFfZmj6g-OoEvWgIGdefOK81StIgnTneOpt8ewhRYRtK0JGy5asUh5mZnYAVdqamWkgtgU1jqDOJ7Pk7PiMiYiLJnokWg38hDgg00N2PZ_KjDumajStsZN5r21Q3_WAxPNaOv0Z4WpSCFUiXTzRaUBCHtNC42qK1v55rhvj2UIg5Oeo7sOh5x4nhEN2v7bJ23GwyR_hhFY1Mh3fNGePQ2opLlcY9dmXk9eGGA',
  },
  {
    id: 'off-3',
    title: 'Flat ₹100 Off on Super Savings',
    description: 'Unlock special discounts on family orders.',
    code: 'SUPERFRETZA',
    discount: '₹100 OFF',
    bgImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArx-O7o0i5J3gkwn5pKInmX34WSDa3cj810iAJGGNYSZdX7qsrrHvw37jEIXpSw1gs9enoev45bEdallUdsx09TIqbWxedluOkn7jw0AH_D5I6p14KTzmrmvayPOnitdB3gRO1gr_Uk9_HDugQXlytC9IWXg8Kkprj7FChNE5oenY34j82DRJdUXBtJs_BzZDidrApDrikr_8ksbeCa364Thg5-fVePbtEVVerKekAEunJHHJOkkAOmC1H8zeudePBTx6vTTrFvg',
  },
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'The Saffron Grill',
    cuisine: 'North Indian • Mughlai • Tandoor',
    rating: 4.8,
    deliveryTime: '25-30 min',
    distance: '2.4 km',
    costForTwo: 350,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCxAmuvEhKKtcjPvpmPHAmNtjnUgNxZZkzsYfYg2T0d16BSeX1v2GVSM7TO7ofBPTGxaWAt3ReBlQHeV7UF87NSHmD-bqrezXMrWA8Vos2a5QthTMw7NZorGOqR5600-ScSe4AGyPZBH31vQkUeUlEpkxnKVXOgxb0e1795o1W514F1ewI2fN6jHt_2IeSUTzJ-5t2iN0Frp9_pwRg2Bz3VxAp54GjX0Sx9EMjH3M2NtEho-kG-imRbr301y-mlkpOBCGjSNx_dIQ',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCxAmuvEhKKtcjPvpmPHAmNtjnUgNxZZkzsYfYg2T0d16BSeX1v2GVSM7TO7ofBPTGxaWAt3ReBlQHeV7UF87NSHmD-bqrezXMrWA8Vos2a5QthTMw7NZorGOqR5600-ScSe4AGyPZBH31vQkUeUlEpkxnKVXOgxb0e1795o1W514F1ewI2fN6jHt_2IeSUTzJ-5t2iN0Frp9_pwRg2Bz3VxAp54GjX0Sx9EMjH3M2NtEho-kG-imRbr301y-mlkpOBCGjSNx_dIQ',
    tags: ['biryani', 'thali', 'north-indian'],
    address: 'Khunta Main Road, Ward 12, Mayurbhanj, Odisha',
    featured: true,
    offers: [
      { code: 'SAFFRON50', text: '50% OFF up to ₹100' },
      { code: 'FREEBY', text: 'Free Sweet Lassi on orders above ₹400' },
    ],
    menu: {
      bestsellers: [
        {
          id: 'food-1-1',
          name: 'Paneer Tikka Butter Masala',
          description: 'Cubes of paneer cooked in a rich, creamy tomato-based gravy with butter and aromatic spices.',
          price: 280,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAyNYD1_EP8cYeyyAnIgb04gE_wCkaMSQ81DoBDSZoVQiuQHZVF0WhwbRU1IpDZC9ttnsn0P46lEVjs4KX5xRBTHkf2c-WppzHqcC6E0Mbe8q38SeNLbfLk5KtiLJhGe7-TGkwRkLGJwMFnHMI3vvggAKE11DY6cfMGo5TEOU_hZTcqa8la0jrZZwiRQUoHbBMFUfHM1vn143zb_41o0u3wk3Ak2pWKsgKleEcjPrX5rPnKhigZkrd4VcktbeqEyA-oXKYf03A5ug',
          rating: 4.9,
          isVeg: true,
          category: 'bestsellers',
          popular: true,
        },
        {
          id: 'food-1-2',
          name: 'Murg Dum Biryani',
          description: 'Fragrant basmati rice layered with succulent chicken pieces and spices, slow-cooked in a sealed clay pot.',
          price: 350,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArx-O7o0i5J3gkwn5pKInmX34WSDa3cj810iAJGGNYSZdX7qsrrHvw37jEIXpSw1gs9enoev45bEdallUdsx09TIqbWxedluOkn7jw0AH_D5I6p14KTzmrmvayPOnitdB3gRO1gr_Uk9_HDugQXlytC9IWXg8Kkprj7FChNE5oenY34j82DRJdUXBtJs_BzZDidrApDrikr_8ksbeCa364Thg5-fVePbtEVVerKekAEunJHHJOkkAOmC1H8zeudePBTx6vTTrFvg',
          rating: 4.8,
          isVeg: false,
          category: 'bestsellers',
          popular: true,
        },
      ],
      mains: [
        {
          id: 'food-1-3',
          name: 'Dal Makhani Special',
          description: 'Overnight slow-cooked black lentils with cream and dollops of butter.',
          price: 220,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCv0kmSpfugcAv-KXjZmr-J_KFbICHVSM-9XHqwZn1taXrzR01rC7Sq0ohjtZCOhSBhd2Wao5XK5xRFipyh5kRgyjVzgw1mYGCGYWM8PK3I8TwjEz6A_Y4rCCJ_jPRyxZjz-snXiiYaB6_N6FICNgUfCP-FE6XDvPtb4mTQKywiqGnSG5aPTPoK8HJ7_bK6eKZT9PPPb0btjWBesZQNYT8FnLC0TL4vjfBTr_RB7fG1OO6kS-1Hpx2RBcGBl0aXK4JjwhU4yZnjfA',
          rating: 4.7,
          isVeg: true,
          category: 'mains',
        },
        {
          id: 'food-1-4',
          name: 'Kadai Murg',
          description: 'Chicken pieces tossed with bell peppers and onion in a spicy masala.',
          price: 320,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjV30BzP-9o9UjLCOoDTzFRsxwF3kLpBgVWhoXJ61GxsCs3gCRpJ5_RkfDsLa0waPU_egtw8tag3gbC4gLKviMV4oJgKHEba1u31_-s3Qqt65O-SHh4EvwUng-EdcIR4jJc59tus-IQ8req5N3DxvG0udamx5a9b7QscO_IQ77QHyFW7WxdFU5YUHGbc_qRqFRKr9Vixz3A0LAZwUqTFAnihh6vYR4lGwY_bulBpbJ9EJanhkbw8TjhlU0L73jd6USVojBGr3ZGA',
          rating: 4.6,
          isVeg: false,
          category: 'mains',
        },
      ],
      desserts: [
        {
          id: 'food-1-5',
          name: 'Shahi Tukda',
          description: 'Deep-fried bread slices soaked in sugar syrup and topped with rich rabri and nuts.',
          price: 120,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAU-8aQY6MZTJF14D7OgMVHJmtm2PfjkCu9U9ojjM8lwK4XDfjjh0K_nRgtKRvxh-E8Rc30hsHQ7JSs4jhaZaqT2NdZxDiy9nA2XfQ5aHYDLIIwi1BXZ3fw3A1oIYG9akLNHKwNUFRdnyxiuCIp21xvOp4XjHSMUK3rJ10amxstvFGyKCuAcrjwC8ZkdiiNdtVx8_obsu2W6fCUhICqXmHP3KIenyVvdIAPf_-NedlFr9wcWKtKtp6dSrl7WsF2glIH56Y0D0iD_A',
          rating: 4.8,
          isVeg: true,
          category: 'desserts',
        },
      ],
      beverages: [
        {
          id: 'food-1-6',
          name: 'Sweet Saffron Lassi',
          description: 'A tall glass of frothy sweet lassi garnished with saffron strands and pistachios.',
          price: 80,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBJxQzg9I1VjsjXr7OQfVKA7x558S_67KzLNGihMOG8nC75yBf4QIF7YqM-99dyrKl5c5KhhP-DbA8n3Z6Bdsl1k4lHvGEGvu5nlb9Kv-dKpXfd2sMgKIpunuACOjDWVrZSJM4uwC2eztiDiU5KxEW6Mel7ScpmSPuxP7ag-eJRLwN45cIFscNG428g9XQ9TWRZC4njHDO1O6z8q6d2AV3XCa4k8ujU_Xk0VnWNrK1VRSHsicvYtVaki8yagJVYklXmp77DUktVlg',
          rating: 4.9,
          isVeg: true,
          category: 'beverages',
        },
        {
          id: 'food-1-7',
          name: 'Fresh Lime Soda',
          description: 'A refreshing glass of fresh lime soda with mint leaves and a lemon slice.',
          price: 60,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7en1u4OajAGBkAP16TodxPd8YNN4BEjnv-Wwc4IG-YnymcUTVxwJvZtiRwGW2yrOYav-bARq-QCJPWj20_GCuOS4oWZtJOsGRiCM-_qcUJ5GbYNpPlEsuXMZbSH3CQZ6EJ1RYFf8wFOAB-Y8p_cRcxk_T9M6tjPpv3vJ7z4c9L4l02hGn7UyctBSJYOLyYpkiRa-Sf2X1D-NO2OOiwKrd_5f0TarULYN-lAVKEdhrG-gE_XfKtjwins6XYPwZ0nEguprGIhPO8w',
          rating: 4.5,
          isVeg: true,
          category: 'beverages',
        },
      ],
    },
  },
  {
    id: 'rest-2',
    name: 'Royal Biryani Junction',
    cuisine: 'Biryani • Hyderabadi • Mughlai',
    rating: 4.6,
    deliveryTime: '15-20 min',
    distance: '1.2 km',
    costForTwo: 250,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAU-8aQY6MZTJF14D7OgMVHJmtm2PfjkCu9U9ojjM8lwK4XDfjjh0K_nRgtKRvxh-E8Rc30hsHQ7JSs4jhaZaqT2NdZxDiy9nA2XfQ5aHYDLIIwi1BXZ3fw3A1oIYG9akLNHKwNUFRdnyxiuCIp21xvOp4XjHSMUK3rJ10amxstvFGyKCuAcrjwC8ZkdiiNdtVx8_obsu2W6fCUhICqXmHP3KIenyVvdIAPf_-NedlFr9wcWKtKtp6dSrl7WsF2glIH56Y0D0iD_A',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAU-8aQY6MZTJF14D7OgMVHJmtm2PfjkCu9U9ojjM8lwK4XDfjjh0K_nRgtKRvxh-E8Rc30hsHQ7JSs4jhaZaqT2NdZxDiy9nA2XfQ5aHYDLIIwi1BXZ3fw3A1oIYG9akLNHKwNUFRdnyxiuCIp21xvOp4XjHSMUK3rJ10amxstvFGyKCuAcrjwC8ZkdiiNdtVx8_obsu2W6fCUhICqXmHP3KIenyVvdIAPf_-NedlFr9wcWKtKtp6dSrl7WsF2glIH56Y0D0iD_A',
    tags: ['biryani', 'north-indian'],
    address: 'Near Bus Stand, Khunta, Odisha',
    featured: false,
    offers: [
      { code: 'ROYAL100', text: 'Flat ₹100 off above ₹399' },
    ],
    menu: {
      bestsellers: [
        {
          id: 'food-2-1',
          name: 'Chicken Dum Biryani (Full)',
          description: 'Aromatic basmati rice cooked with spice-infused chicken and standard herbs.',
          price: 240,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArx-O7o0i5J3gkwn5pKInmX34WSDa3cj810iAJGGNYSZdX7qsrrHvw37jEIXpSw1gs9enoev45bEdallUdsx09TIqbWxedluOkn7jw0AH_D5I6p14KTzmrmvayPOnitdB3gRO1gr_Uk9_HDugQXlytC9IWXg8Kkprj7FChNE5oenY34j82DRJdUXBtJs_BzZDidrApDrikr_8ksbeCa364Thg5-fVePbtEVVerKekAEunJHHJOkkAOmC1H8zeudePBTx6vTTrFvg',
          rating: 4.7,
          isVeg: false,
          category: 'bestsellers',
          popular: true,
        },
      ],
      mains: [
        {
          id: 'food-2-2',
          name: 'Egg Biryani Special',
          description: 'Delicious egg biryani cooked in slow handi.',
          price: 180,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArx-O7o0i5J3gkwn5pKInmX34WSDa3cj810iAJGGNYSZdX7qsrrHvw37jEIXpSw1gs9enoev45bEdallUdsx09TIqbWxedluOkn7jw0AH_D5I6p14KTzmrmvayPOnitdB3gRO1gr_Uk9_HDugQXlytC9IWXg8Kkprj7FChNE5oenY34j82DRJdUXBtJs_BzZDidrApDrikr_8ksbeCa364Thg5-fVePbtEVVerKekAEunJHHJOkkAOmC1H8zeudePBTx6vTTrFvg',
          rating: 4.4,
          isVeg: false,
          category: 'mains',
        },
      ],
      desserts: [],
      beverages: [],
    },
  },
  {
    id: 'rest-3',
    name: 'Pizza Express & Burger Bar',
    cuisine: 'Pizza • Fast Food • Burgers',
    rating: 4.5,
    deliveryTime: '18-22 min',
    distance: '3.1 km',
    costForTwo: 300,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPWT-waWRecQTq2KTGIgFv1spM-RjnQoa3yYSfAFFfZmj6g-OoEvWgIGdefOK81StIgnTneOpt8ewhRYRtK0JGy5asUh5mZnYAVdqamWkgtgU1jqDOJ7Pk7PiMiYiLJnokWg38hDgg00N2PZ_KjDumajStsZN5r21Q3_WAxPNaOv0Z4WpSCFUiXTzRaUBCHtNC42qK1v55rhvj2UIg5Oeo7sOh5x4nhEN2v7bJ23GwyR_hhFY1Mh3fNGePQ2opLlcY9dmXk9eGGA',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPWT-waWRecQTq2KTGIgFv1spM-RjnQoa3yYSfAFFfZmj6g-OoEvWgIGdefOK81StIgnTneOpt8ewhRYRtK0JGy5asUh5mZnYAVdqamWkgtgU1jqDOJ7Pk7PiMiYiLJnokWg38hDgg00N2PZ_KjDumajStsZN5r21Q3_WAxPNaOv0Z4WpSCFUiXTzRaUBCHtNC42qK1v55rhvj2UIg5Oeo7sOh5x4nhEN2v7bJ23GwyR_hhFY1Mh3fNGePQ2opLlcY9dmXk9eGGA',
    tags: ['pizza', 'burgers'],
    address: 'College Square, Khunta, Odisha',
    featured: true,
    offers: [
      { code: 'PIZZA20', text: '20% OFF on all Pizzas' },
    ],
    menu: {
      bestsellers: [
        {
          id: 'food-3-1',
          name: 'Double Truffle Burger',
          description: 'Premium artisan burger with double truffled cheese patty, fresh heirloom tomatoes, and crisp lettuce.',
          price: 549,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKuz63icQv1veP9wJJpQaYbn0127nxvam4JLpMIlwxi_YnbXjlBXpJBfONPLimMIrQRkqYuDeE7EyQcbHCBsmu5Xl89s5IjMSQs_zZY8tx2hmAiLmAM2Yrzq-gvmzDNpnmTfvQ2PqwbpIZQX7zrFLAcBheVcrRuuWFdR31ltaNQeWSYBdSWMBWD6aZBX9IMLJo0A_NeHMcQDeWh65rtE8bhFnRYxMBtLxbGiw1GNJ9r2IMzW6QNLHcf_ib2RK6qXbRgxp-_kU0WQ',
          rating: 4.8,
          isVeg: false,
          category: 'bestsellers',
          popular: true,
        },
      ],
      mains: [
        {
          id: 'food-3-2',
          name: 'Cheesy Paneer Pizza',
          description: 'Double cheese, fresh onion, and soft paneer chunks.',
          price: 299,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPWT-waWRecQTq2KTGIgFv1spM-RjnQoa3yYSfAFFfZmj6g-OoEvWgIGdefOK81StIgnTneOpt8ewhRYRtK0JGy5asUh5mZnYAVdqamWkgtgU1jqDOJ7Pk7PiMiYiLJnokWg38hDgg00N2PZ_KjDumajStsZN5r21Q3_WAxPNaOv0Z4WpSCFUiXTzRaUBCHtNC42qK1v55rhvj2UIg5Oeo7sOh5x4nhEN2v7bJ23GwyR_hhFY1Mh3fNGePQ2opLlcY9dmXk9eGGA',
          rating: 4.6,
          isVeg: true,
          category: 'mains',
        },
      ],
      desserts: [],
      beverages: [],
    },
  },
  {
    id: 'rest-4',
    name: 'Green Garden Healthy Cafe',
    cuisine: 'Salads • Cafe • Organic',
    rating: 4.7,
    deliveryTime: '20-25 min',
    distance: '1.8 km',
    costForTwo: 400,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCw8Tadnnt0MKfCkzGzyszb76HX7CfGw8xA5OCYBve7nzXrWsKDm_0JBLm9YD4Cr-ZNUz1CRmSNoq-kzrA-TX-8JwDajNYIYf2T6l1S7XztpMtzGUxyGVqvbCggsVs9nLYUokb8H5V8u-uaHCsoyxmuKaFQ4jHkJEKbx8f2pLgYI65-y3nDZ2Orx3uDwi3G7PUc77P2zbCl1QyY5JmtwWbafXciC-5pO2G44o4vyTshU6y1pDkF328n0CbKDUWSk4hXXg_n5KHDlQ',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCw8Tadnnt0MKfCkzGzyszb76HX7CfGw8xA5OCYBve7nzXrWsKDm_0JBLm9YD4Cr-ZNUz1CRmSNoq-kzrA-TX-8JwDajNYIYf2T6l1S7XztpMtzGUxyGVqvbCggsVs9nLYUokb8H5V8u-uaHCsoyxmuKaFQ4jHkJEKbx8f2pLgYI65-y3nDZ2Orx3uDwi3G7PUc77P2zbCl1QyY5JmtwWbafXciC-5pO2G44o4vyTshU6y1pDkF328n0CbKDUWSk4hXXg_n5KHDlQ',
    tags: ['cafe'],
    address: 'Near Medical College, Khunta, Odisha',
    featured: false,
    offers: [
      { code: 'HEALTHY15', text: '15% OFF on salads' },
    ],
    menu: {
      bestsellers: [
        {
          id: 'food-4-1',
          name: 'Mediterranean Salad Bowl',
          description: 'Kalamata olives, premium feta cheese, cherry tomatoes, and cucumber drizzled with light olive oil.',
          price: 320,
          image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCw8Tadnnt0MKfCkzGzyszb76HX7CfGw8xA5OCYBve7nzXrWsKDm_0JBLm9YD4Cr-ZNUz1CRmSNoq-kzrA-TX-8JwDajNYIYf2T6l1S7XztpMtzGUxyGVqvbCggsVs9nLYUokb8H5V8u-uaHCsoyxmuKaFQ4jHkJEKbx8f2pLgYI65-y3nDZ2Orx3uDwi3G7PUc77P2zbCl1QyY5JmtwWbafXciC-5pO2G44o4vyTshU6y1pDkF328n0CbKDUWSk4hXXg_n5KHDlQ',
          rating: 4.8,
          isVeg: true,
          category: 'bestsellers',
          popular: true,
        },
      ],
      mains: [],
      desserts: [],
      beverages: [],
    },
  },
];

export const MOCK_USER: UserProfile & { addresses: any[]; orders: any[] } = {
  name: 'Jogesh Dwivedi',
  email: 'jogesh.dwivedi@fretza.com',
  phone: '+91 98765 43210',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDCQNEcS9UrzH3O090fWr5hpqlNyVksZ6JQ8WXY-_bkWQmWKx3ow0-krjdyL64WAEM30crkxpqq9-kx6NWrT5ZXidiZd03gIXp-8P8dNcPP0dwGD209vtpjar-C_f7-AeTk1a0ba2_5J4JH2iJKUDwn7_De7noc9Nn5H9wjMokSzFA6_4hifTqT-hcXrAWr6f18kYMVRn2rLHPFTFD2HhfwezXG2_sSuW_LHN1sPPNP5okF9QlD4Y283LR-uY2NoNjcubFNqfx0AQ',
  addresses: [
    {
      id: 'addr-1',
      label: 'Home',
      details: '42, Green Valley Apartments, Khunta Main Road, Ward 12, Mayurbhanj, Odisha - 757019',
      isDefault: true,
    },
    {
      id: 'addr-2',
      label: 'Work',
      details: 'Block B, TechHub Plaza, Khunta Industrial Area, Mayurbhanj, Odisha - 757021',
      isDefault: false,
    },
  ],
  orders: [
    {
      id: 'ORD-9824',
      restaurantId: 'rest-1',
      restaurantName: 'The Saffron Grill',
      items: [
        {
          menuItem: {
            id: 'food-1-2',
            name: 'Murg Dum Biryani',
            price: 350,
            image: '',
            isVeg: false,
            category: 'bestsellers',
          },
          quantity: 1,
        },
        {
          menuItem: {
            id: 'food-1-6',
            name: 'Sweet Saffron Lassi',
            price: 80,
            image: '',
            isVeg: true,
            category: 'beverages',
          },
          quantity: 2,
        },
      ],
      subtotal: 510,
      deliveryFee: 0,
      discount: 50,
      grandTotal: 485,
      date: 'July 5, 2026',
      status: 'Delivered',
      deliveryAddress: '42, Green Valley Apartments, Khunta Main Road, Ward 12, Mayurbhanj, Odisha - 757019',
      paymentMethod: 'Cash on Delivery',
    },
    {
      id: 'ORD-7215',
      restaurantId: 'rest-3',
      restaurantName: 'Pizza Express & Burger Bar',
      items: [
        {
          menuItem: {
            id: 'food-3-1',
            name: 'Double Truffle Burger',
            price: 549,
            image: '',
            isVeg: false,
            category: 'bestsellers',
          },
          quantity: 1,
        },
      ],
      subtotal: 549,
      deliveryFee: 0,
      discount: 0,
      grandTotal: 576,
      date: 'July 1, 2026',
      status: 'Delivered',
      deliveryAddress: 'Block B, TechHub Plaza, Khunta Industrial Area, Mayurbhanj, Odisha - 757021',
      paymentMethod: 'Card on Delivery',
    },
  ],
};
